CREATE SEQUENCE hotel_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE hotel (
  code BIGINT GENERATED BY DEFAULT AS SEQUENCE hotel_id_seq PRIMARY KEY,
  title VARCHAR(255),
  address VARCHAR(255),
  cnpj VARCHAR(255),
  description VARCHAR(255),
  priceNWK FLOAT,
  priceNWE FLOAT,
  priceAWK FLOAT,
  priceAWE FLOAT,
  rating INT,
  blackoutI DATE,
  blackoutE DATE
--  priceNormalWeek INT
--  priceNormalWeekend FLOAT,
--  priceAwardWeek FLOAT,
--  priceAwardWeekend FLOAT,
--  rating INT,
--  blackoutStart DATE,
--  blackoutEnd DATE
);